namespace FEnum
{
    public enum DiceGrade
    {
        DICE_GRADE_NONE,
        DICE_GRADE_NORMAL,
        DICE_GRADE_RARE,
        DICE_GRADE_EPIC,
        DICE_GRADE_LEGEND,
    }

    public enum StorePurchaseResult
    {
        STORE_PURCHASE_RESULT_SUCCESS,
        STORE_PURCHASE_RESULT_NOT_ENOUGH_MONEY,
        STORE_PURCHASE_RESULT_SOLDOUT,
        STORE_PURCHASE_RESULT_INVALID_GOODS,
    }

    public enum BattlefieldPurchaseResult
    {
        BATTLEFIELD_PURCHASE_RESULT_SUCCESS,
        BATTLEFIELD_PURCHASE_RESULT_NOT_ENOUGH_MONEY,
        BATTLEFIELD_PURCHASE_RESULT_INVALID,
        BATTLEFIELD_PURCHASE_RESULT_ALEADY_ACQUIRED,
    }

    public enum DiceUpgradeResult
    {
        DICE_UPGRADE_RESULT_SUCCESS,
        DICE_UPGRADE_RESULT_INVALID_DICE,
        DICE_UPGRADE_RESULT_NOT_ENOUGH_MONEY,
        DICE_UPGRADE_RESULT_NOT_ENOUGH_DICE,
        DICE_UPGRADE_RESULT_MAX_LEVEL,
    };
}